// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF8mlbfAV3jD-d0yMuVj1kOEx5XTFajlQ',
    appId: '1:602613772724:web:8ff5ffbca0d0392aa7c2e1',
    messagingSenderId: '602613772724',
    projectId: 'todoflutter-5db46',
    authDomain: 'todoflutter-5db46.firebaseapp.com',
    storageBucket: 'todoflutter-5db46.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEHPCO7OUbgj8qr2ChbTiMrROj4llGGjo',
    appId: '1:602613772724:android:fd1cce8e1b1b88dda7c2e1',
    messagingSenderId: '602613772724',
    projectId: 'todoflutter-5db46',
    storageBucket: 'todoflutter-5db46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3OAfIa6DSnupUI4y06jeHGbUcBh3Rm_o',
    appId: '1:602613772724:ios:50ed915554cda4eea7c2e1',
    messagingSenderId: '602613772724',
    projectId: 'todoflutter-5db46',
    storageBucket: 'todoflutter-5db46.appspot.com',
    iosClientId: '602613772724-e73mig1p25prf5muo52u5cg7dq5apjtj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTodo',
  );
}
